import './globals.css'
import { Inter } from 'next/font/google'
import Container from "@/components/layout/Container";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FMW Tax Return Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Container className="py-10" asChild>
        <main>
          {children}
        </main>
      </Container>
      </body>
    </html>
  )
}
